## 22127260-Bùi Công Mậu
## 22127400-Thái Hữu Thọ

In [2]:
from sklearn.preprocessing import MinMaxScaler 
from sklearn.preprocessing import LabelEncoder
import pandas as pd

In [8]:
#Đọc file train sau khi preprocessing
train_new_data = pd.read_csv('../Data/train_cleaned.csv')

#Áp dụng Min Max Scaling cho các biến số trừ cột "id"
scaler = MinMaxScaler()
num_col = [col for col in train_new_data.columns if train_new_data[col].dtype in ['int64', 'float64'] and col != 'id']
train_new_data[num_col] = scaler.fit_transform(train_new_data[num_col])

if 'feature_12' in train_new_data.columns:

    # Bỏ cột feature_12 gốc
    train_new_data = train_new_data.drop(columns=['feature_12'])

# Xác định các cột categorical (các cột kiểu object)
categorical_cols = train_new_data.select_dtypes(include=['object']).columns.tolist()

# Mã hóa các cột categorical bằng LabelEncoder
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    train_new_data[col] = le.fit_transform(train_new_data[col].astype(str))
    label_encoders[col] = le

# Lưu lại file train đã chuẩn hóa
train_new_data.to_csv('../Data/train_normalized.csv', index=False)

# In ra 5 dòng đầu tiên của file train sau khi chuẩn hóa
train_new_data.head()

,id,Age,Gender,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_13,feature_14,feature_15,feature_16,target
0,0,0.021739,0,0.066988,1,0.25,0,2,0.361397,2,2,0.222222,0.894737,0.131148,0.500,3,0,3,2,0.572203
1,1,0.456522,0,0.211186,0,0.75,2,1,0.238002,0,1,0.111111,0.631579,0.717668,0.125,0,1,1,2,0.293834
2,2,0.108696,1,0.170678,0,0.75,1,2,0.792879,1,2,0.111111,0.736842,0.533560,0.250,1,1,3,2,0.109861
3,3,0.065217,1,0.945719,1,0.50,0,1,0.156695,0,0,0.111111,0.000000,0.122040,0.000,3,1,0,0,0.149628
4,4,0.065217,1,0.264340,3,0.25,0,2,0.322378,0,2,0.000000,0.421053,0.542805,0.375,3,1,3,2,0.402089

In [11]:
#Đọc file test sau khi preprocessing
test_new_data = pd.read_csv('../Data/test_cleaned.csv')

#Áp dụng Min Max Scaling cho các biến số trừ cột "id"
scaler = MinMaxScaler()
num_col = [col for col in test_new_data.columns if test_new_data[col].dtype in ['int64', 'float64'] and col != 'id']
test_new_data[num_col] = scaler.fit_transform(test_new_data[num_col])

if 'feature_12' in test_new_data.columns:

    # Bỏ cột feature_12 gốc
    test_new_data = test_new_data.drop(columns=['feature_12'])

# Xác định các cột categorical (các cột kiểu object)
categorical_cols = test_new_data.select_dtypes(include=['object']).columns.tolist()

# Mã hóa các cột categorical bằng LabelEncoder
label_encoders = {}
for col in categorical_cols:
    le = LabelEncoder()
    test_new_data[col] = le.fit_transform(test_new_data[col].astype(str))
    label_encoders[col] = le

#Lưu lại file test đã được chuẩn hóa vào file mới 
test_new_data.to_csv('../Data/test_normalized.csv', index=False)

#In ra 5 dòng đầu tiên của file test sau khi chuẩn hóa 
test_new_data.head()

,id,Age,Gender,feature_0,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,feature_10,feature_11,feature_13,feature_14,feature_15,feature_16
0,1200000,0.217391,0,0.015387,2,1.00,0,2,0.106754,0,0,0.111653,1.000000,0.533524,0.000,3,1,3,2
1,1200001,0.282609,0,0.840221,1,0.50,2,2,0.208394,1,2,0.111653,0.736842,0.131148,0.875,1,1,2,0
2,1200002,0.630435,0,0.113937,0,0.00,3,3,0.403261,2,1,0.111653,0.842105,0.945355,1.000,0,1,1,1
3,1200003,0.217391,0,0.202820,0,0.75,3,2,0.061972,1,1,0.111111,0.157895,0.856102,0.500,3,1,0,2
4,1200004,0.130435,1,0.072409,0,0.50,1,3,0.181095,1,2,0.111653,0.736842,0.828780,0.750,0,0,3,2